var a=10;
var b=20;
var c=a+b;
var d=a-b;
var e=a*b;
var f=b**a;
var g=a/b;
var h=a%b;
var i=++a;
var j=--b;
console.log(c);
console.log(d);
    console.log(e);
        console.log(f);
            console.log(g);
                console.log(h);
                    console.log(i);
                        console.log(j);